db:
  postgres:
    url: ${POSTGRES_URI}
auth:
  jwt:
    secret: ${JWT_SECRET}
    algorithm: ${JWT_ALGORITHM}
  token:
    expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh_token:
    expiration: ${REFRESH_TOKEN_EXPIRATION}
