version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: /bin/sh ./run_server.sh
    depends_on:
      - db-postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_URI=${POSTGRES_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - ACCESS_TOKEN_EXPIRATION=${ACCESS_TOKEN_EXPIRATION}
      - DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}
      - DOCKERHUB_ACCESS_TOKEN=${DOCKERHUB_ACCESS_TOKEN}
    networks:
      - match_and_watch
  db-postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ms-user
    networks:
      - match_and_watch
      
networks:
  match_and_watch:
    external: true

